version: "3"


volumes:
  postgres_data: {}

services:
  postgres:
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
    ports:
      - '${DB_PORT:-5431}:5432'
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    restart: "unless-stopped"
